baseURL = 'https://johnmayou.com/'
languageCode = 'en-us'
title = 'John Mayou'
enableEmoji = true

[params]
  description = "I'm a developer living in Minneapolis, MN. I currently work at SPS Commerce."

[markup.highlight]
  style = "github-dark"